### ISSUE TITLE
Can't find repositories on Tower 2.3.1

### ISSUE THREAD

**Issue by jherran** [cjlucas/tower-alfred-workflow#12]
After some research, if I change the BOOKMARKS_PATH from:
BOOKMARKS_PATH = "~/Library/Application Support/com.fournova.Tower2/bookmarks.plist"

to:
BOOKMARKS_PATH = "~/Library/Application Support/com.fournova.Tower2/bookmarks-v2.plist"

The new repositories will be shown again.

**Comment by jousch** [comment]
This is unfortunately also wrong. Tower 2 uses a sqlite3 database for handling bookmarks.

It would be nice if the workflow could support this (e.g. by exporting the bookmarks on the fly (with caching)).

**Comment by jousch** [comment]
The necessary information is saved under:
```
sqlite3 ~/Library/Application Support/com.fournova.Tower2/Tower.sqlite3
# get Tables:
.tables;
# show schema of ZGTBOOKMARK
.schema ZGTBOOKMARK;
# show content
SELECT * FROM ZGTBOOKMARK;
# show name and fileurl of bookmarks
SELECT ZNAME,ZFILEURL FROM ZGTBOOKMARK WHERE ZTYPE = 2;
```

With the last line we get all necessary fields. These must be processed in a readable format for the worklow.

**Comment by jousch** [comment]
The export could look like (sqlite3 must be installed (e.g. with homebrew)):

```
#!/bin/bash
./bin/sqlite3 ~/Library/Application Support/com.fournova.Tower2/Tower.sqlite3 <<!
.headers on
.mode csv
.output bookmarks.csv
SELECT ZNAME,ZFILEURL FROM ZGTBOOKMARK WHERE ZTYPE = 2;
!
```

**Comment by jousch** [comment]
@cjlucas do you think you could upgrade this workflow that it also works with actual versions of Tower2? That would be really cool!

**Comment by cjlucas** [comment]
Does Tower 2 not produce a bookmarks plist anymore?

**Comment by jousch** [comment]
There is a plist file, but it seems like it is not updated anymore. Also a second plist suffixed one from another date. Maybe it was backup'd before an specific update of Tower?

Should I contact the support of Fournova? Maybe it's just a bug of a actual Tower version. Is your plist file updated when you're add a new repo?

Merry christmas btw,
Cheers
Josef

**Comment by cjlucas** [comment]
`bookmarks-v2.plist` is still being updated for me. I'm aware that the primary method of obtaining the bookmarks is through their Core Data database. But as long as the plist is still supported, I'm inclined to stick with it for now.

If this changes in the future, I'll certainly take your solution into consideration.

Thanks for your support.

**Comment by jousch** [comment]
Ok, so I have to contact the support as this file isn't updating in my installation.

Thanks for your reply!

**Comment by jousch** [comment]
Ah OK! Now I've understand it. I have to change to bookmarks-v2.plist. Maybe it's better to update the workflow, so that new users of the workflow have a working version without manually fixing it?

**Comment by GaryKing** [comment]
Anyone know how often CoreData writes to the plist file? Mine hasn't updated in 36 hours, and I've noticed this happen several times.

**Comment by jousch** [comment]
Do anybody else have troubles using this workflow with alfred version 3.1 Build 718?

**Comment by bryankulba** [comment]
I'm also having trouble with this workflow on 3.1 718... I don't think the plist is being updated so I wonder if it's the recent Tower update and not this workflow or Alfred.
