### ISSUE TITLE
Missing a repo

### ISSUE THREAD

**Issue by LeonardoGentile** [cjlucas/tower-alfred-workflow#18]
Hello,
I've been using this for years, but recently it stopped to work, maybe because of new osx version or because I've upgraded tower.
Anyway I've installed a fresh version of your repo (today), then changed the path of Tower from `open_repo.bash` and get things to (almost) work.

In fact I have two repo in Tower that start with a similar name, one is called `.dotfiles` the other one is called `.dotfiles-private`.
No matter what the `.dotfiles-private` will always shadow the other one, meaning that `.dotfiles` repo will never show up.

**Comment by cjlucas** [comment]
I've tried to reproduce your issue by adding a repo called ".dotfiles" and ".dotfiles-private" to tower, than typing "tower dotfiles" into Alfred, but both entries show up for me.

Can you check `~/Library/Application Support/com.fournova.Tower2/bookmarks-v2.plist` and see if there are entries for both repos?

**Comment by LeonardoGentile** [comment]
Indeed it wasn't there!
I'm not sure why, I've removed and re-added the repo to tower and now it works 👍
